import { TBorderConfig, TBorderType, TDisplaySettings, TTopography } from 'src/types/map.types';

export const NATION_COLORS = [
  '#e6194b',
  '#3cb44b',
  '#ffe119',
  '#4363d8',
  '#f58231',
  '#911eb4',
  '#46f0f0',
  '#f032e6',
  '#bcf60c',
  '#fabebe',
  '#008080',
  '#e6beff',
  '#9a6324',
  '#fffac8',
  '#800000',
  '#aaffc3',
  '#808000',
  '#ffd8b1',
  '#4D4DC1',
  '#808080',
  '#ffffff',
  '#ffd700',
  '#00ff7f',
  '#ff1493',
  '#ff4500',
  '#2e8b57',
  '#8b008b',
  '#daa520',
  '#00ced1',
  '#ff8c00',
  '#adff2f',
  '#ff00ff',
  '#1e90ff',
  '#fa8072',
  '#7fffd4',
  '#b22222',
  '#ffdead',
  '#4b0082',
  '#006400',
  '#bc8f8f',
];

export const DEFAULT_CONFIG: {
  seed: string;
  cellCount: number;
  seaLevel: number;
  topography: TTopography;
  nationCount: number;
  climateControl: {
    temperatureOffset: number;
    temperatureContrast: number;
    precipitationScale: number;
    precipitationOffset: number;
    humanImpact: number;
  };
  displaySettings: TDisplaySettings;
} = {
  seed: 'world-001',
  cellCount: 10000,
  seaLevel: 0.5,
  topography: 'balanced',
  nationCount: 8,
  climateControl: {
    temperatureOffset: 0.2,
    temperatureContrast: 1.5,
    precipitationScale: 1.5,
    precipitationOffset: 0.3,
    humanImpact: 0.5,
  },
  displaySettings: {
    landform: false,
    landformRelief: false,
    biome: false,
    biomeRelief: true,
    population: false,
    temperature: false,
    precipitation: false,
    rainShadow: false,
    economy: false,
    rivers: false,
    nationBorders: false,
    nationFill: false,
    provinceBorders: false,
    ethnicBorders: false,
    ethnicFill: false,
    ethnicLabels: false,
    labels: false,
    cellData: false,
  },
};

export const MAP_VIEWPORT_CONFIG = {
  width: 1200,
  height: 760,
  minCells: 100,
  maxCells: 10000,
};

export const TOPOGRAPHY_CONFIG = {
  boundary: {
    collisionBaseCount: 7,
    collisionExtraCount: 4,
    riftBaseCount: 4,
    riftExtraCount: 3,
    halfLengthMin: 0.11,
    halfLengthRange: 0.25,
    strengthBase: 0.75,
    strengthRange: 0.6,
    influenceWidth: 0.12,
    collisionScale: 0.26,
    riftScale: 0.2,
  },
  seeds: {
    upliftCount: 10,
    basinCount: 8,
    xMargin: 0.03,
    yMargin: 0.03,
    span: 0.94,
    upliftRadiusBase: 0.06,
    upliftRadiusRange: 0.1,
    basinRadiusBase: 0.08,
    basinRadiusRange: 0.12,
    upliftAmplitudeBase: 0.2,
    upliftAmplitudeRange: 0.22,
    basinAmplitudeBase: 0.16,
    basinAmplitudeRange: 0.18,
  },
  warp: { frequency: 2.2, strength: 0.2, secondaryFrequency: 5.1, secondaryStrength: 0.08 },
  noise: {
    macroDivisor: 1.58,
    secondaryFrequency: 1.6,
    secondaryDivisor: 1.95,
    coastFrequency: 8.4,
    jaggedFrequency: 5.2,
    jaggedBase: 0.72,
    jaggedRange: 0.62,
    fbm: { octaves: 8, persistence: 0.53, lacunarity: 2.08 },
    ridged: { octaves: 7, persistence: 0.49, lacunarity: 2.2, sharpness: 1.75 },
    billow: { octaves: 7, persistence: 0.5, lacunarity: 1.96 },
  },
  shelf: { edgeOffset: 0.005, edgeRange: 0.18, weight: 0.05 },
  blend: {
    macro: 0.3,
    secondary: 0.18,
    ridged: 0.22,
    billow: 0.14,
    erosionMask: 0.12,
    upliftField: 0.3,
    tectonicUplift: 0.38,
    coastNoise: 0.08,
    basinField: 0.26,
    tectonicRift: 0.24,
    maxUplift: 1.2,
    maxRift: 1,
  },
  mountainRecovery: { quantileStart: 0.86, peakBoostMax: 0.14 },
};

export const PRESET_CONFIG = {
  balanced: {
    rangeBands: { count: 7, amplitude: 0.2, width: 0.11 },
    valleyBands: { count: 5, depth: 0.12, width: 0.12 },
    edgeShelfStrength: 0.24,
    smoothFactor: 0.2,
  },
  ranges: {
    rangeBands: { count: 10, amplitude: 0.24, width: 0.09 },
    valleyBands: { count: 4, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.2,
    smoothFactor: 0.16,
  },
  rifted: {
    rangeBands: { count: 8, amplitude: 0.17, width: 0.1 },
    valleyBands: { count: 8, depth: 0.16, width: 0.08 },
    globalScale: { offset: -0.02, scale: 0.98 },
    edgeShelfStrength: 0.22,
    smoothFactor: 0.18,
  },
  archipelago: {
    majorIslandMin: 1,
    majorIslandMax: 2,
    mediumIslandBase: 4,
    mediumIslandExtra: 3,
    smallIslandBase: 16,
    smallIslandExtra: 8,
    valleyBands: { count: 7, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.3,
    smoothFactor: 0.14,
  },
};

export const RIVER_CONFIG = {
  minFluxToFormRiver: 30,
  landWaterThreshold: 0.2,
  cellsNumberModifierExp: 0.25,
  depression: { maxIterations: 200, epsilon: 0.0001, coastLift: 0.0015 },
  width: { fluxFactor: 500, maxFluxWidth: 1, lengthFactor: 200, minWidth: 0.8, maxWidth: 4.8 },
  meander: { base: 0.5, minSegmentLength: 16 },
  minRiverCells: 6,
};

export const BORDER_CONFIG: Record<TBorderType, TBorderConfig> = {
  nation: {
    landformCost: {
      marine_deep: 1.2,
      marine_shallow: 1.2,
      coast: 0.9,
      lake: 1.2,
      plain: 1.1,
      valley: 0.95,
      hills: 1.9,
      mountain: 7.8,
      plateau: 1.8,
      volcanic_field: 8.6,
    },
    biomeCost: {
      unknown: 1,
      plain: 1,
      ice: 1.8,
      tundra: 1.8,
      boreal_forest: 1.25,
      temperate_forest: 1.2,
      tropical_forest: 1.35,
      grassland: 1.05,
      savanna: 1.1,
      steppe: 2.4,
      desert_hot: 2.1,
      desert_cold: 2.1,
      wetland: 1.9,
      montane_shrub: 1.45,
      freshwater: 1.2,
      marine: 1.2,
    },
    penalty: { riverCross: 7.8, lakeCross: 8.4, ridgeCross: 10.5, shorelineEdgeBias: -0.3 },
    fragmentation: {
      maxMountainOwnersPerCluster: 2,
      largeMountainClusterMinCells: 10,
      clusterSplitPenalty: 2.8,
    },
    smoothness: { edgeNoiseWeight: 0.16, jaggedPenalty: 0.5 },
  },
  province: {
    landformCost: {
      marine_deep: 1.2,
      marine_shallow: 1.2,
      coast: 1.15,
      lake: 1.2,
      plain: 1,
      valley: 0.95,
      hills: 1.6,
      mountain: 3.5,
      plateau: 1.7,
      volcanic_field: 4.2,
    },
    biomeCost: {
      unknown: 1,
      plain: 1,
      ice: 1.6,
      tundra: 1.6,
      boreal_forest: 1.45,
      temperate_forest: 1.35,
      tropical_forest: 1.5,
      grassland: 1.05,
      savanna: 1.1,
      steppe: 2.1,
      desert_hot: 1.9,
      desert_cold: 1.9,
      wetland: 1.85,
      montane_shrub: 1.4,
      freshwater: 1.2,
      marine: 1.2,
    },
    penalty: { riverCross: 3.4, lakeCross: 4.2, ridgeCross: 4.8, shorelineEdgeBias: -0.2 },
    fragmentation: {
      maxMountainOwnersPerCluster: 3,
      largeMountainClusterMinCells: 7,
      clusterSplitPenalty: 1.4,
    },
    smoothness: { edgeNoiseWeight: 0.08, jaggedPenalty: 0.25 },
  },
};

export const GEOPOLITICAL_CONFIG = {
  minLandRatio: 0,
  minLandCells: 10,
  frontierNoise: 0.22,
  hubs: { smallNationMinLand: 450, mediumNationMinLand: 900, maxHubsPerNation: 3 },
  ethnic: {
    majorGroupMin: 6,
    majorGroupMax: 12,
    dominantShareMin: 0.5,
    dominantShareMax: 0.8,
    secondaryShareMin: 0.1,
    secondaryShareMax: 0.3,
    crossBorderBlend: 0.72,
    fragmentationLevel: 0.38,
    terrainInfluenceStrength: 1,
    distancePenalty: 0.045,
    smoothingPasses: 1,
    minorityClusterMin: 5,
  },
};
