import type { TSiteMetadata } from 'src/types/global';
import type { TTerrain, TTerrainConfig, TTerrainPresetOption } from 'src/types/map.types';
import { ImageAsset } from './ImageAssets';

export const APP_NAME = 'Fantasy World';

export const siteMetadata: TSiteMetadata = {
  title: APP_NAME,
  description:
    'Procedural fantasy world map generator with deterministic seeds, terrain simulation, hydrology, nations, and ethnic regions.',
  url: 'https://fantasy.peter-present.xyz/',
  siteName: APP_NAME,
  twitterHandle: 'PhamHon08928762',
  icon: ImageAsset.icon,
  image: ImageAsset.thumbnail,
  keywords:
    'fantasy map generator, procedural world generation, seeded map generation, worldbuilding tool, terrain and river simulation, nation borders, ethnic regions',
};

export const TERRAIN_PRESET_OPTIONS: TTerrainPresetOption[] = [
  { label: 'Balanced', value: 'balanced' },
  { label: 'Archipelago', value: 'archipelago' },
  { label: 'Ranges', value: 'ranges' },
  { label: 'Rifted', value: 'rifted' },
];

export const TERRAIN_CONFIG: Record<TTerrain, TTerrainConfig> = {
  'deep-water': {
    label: 'Ocean',
    color: '#0a192f',
    icon: '🌊',
    isWater: true,
    isHydrologyWater: true,
    isMarineWater: true,
    isRenderWater: true,
    sizeFactor: 1,
    logisticsCost: 1.5,
    logisticsRisk: 0,
    baseSuitability: 0,
    baseWeight: 0,
    cityFactor: 0,
    flatness: 0,
    economyFactor: 0,
    safetyScore: 0,
  },
  'shallow-water': {
    label: 'Sea',
    color: '#1a3a6d',
    icon: '🌊',
    isWater: true,
    isHydrologyWater: true,
    isMarineWater: true,
    isRenderWater: true,
    sizeFactor: 1,
    logisticsCost: 1.5,
    logisticsRisk: 0,
    baseSuitability: 0,
    baseWeight: 0,
    cityFactor: 0,
    flatness: 0,
    economyFactor: 0.4,
    safetyScore: 0,
  },
  'inland-sea': {
    label: 'Inland Sea',
    color: '#255497',
    icon: '🌊',
    isWater: true,
    isHydrologyWater: true,
    isMarineWater: true,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 1.5,
    logisticsRisk: 0,
    baseSuitability: 0,
    baseWeight: 0,
    cityFactor: 0,
    flatness: 0,
    economyFactor: 0.4,
    safetyScore: 0,
  },
  lake: {
    label: 'Lake',
    color: '#1e81b0',
    icon: '🏞️',
    isWater: true,
    isHydrologyWater: true,
    isMarineWater: false,
    isRenderWater: true,
    sizeFactor: 1,
    logisticsCost: 1.5,
    logisticsRisk: 0,
    baseSuitability: 0.12,
    baseWeight: 0,
    cityFactor: 0,
    flatness: 0,
    economyFactor: 1.2,
    safetyScore: 0,
  },
  coast: {
    label: 'Coast',
    color: '#f2d492',
    icon: '🏖️',
    isHydrologyWater: true,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 1.35,
    logisticsRisk: 0,
    baseSuitability: null,
    baseWeight: 0.8,
    cityFactor: 0.92,
    flatness: 0.82,
    economyFactor: 1.8,
    safetyScore: -0.05,
  },
  plains: {
    label: 'Plains',
    color: '#5eba7d',
    icon: '🌾',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 1,
    logisticsRisk: 0,
    baseSuitability: null,
    baseWeight: 1,
    cityFactor: 1,
    flatness: 1,
    economyFactor: 1.3,
    safetyScore: 0.25,
  },
  valley: {
    label: 'Valley',
    color: '#8bc34a',
    icon: '🌿',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 1,
    logisticsRisk: 0,
    baseSuitability: null,
    clusterMin: 5,
    baseWeight: 0.7,
    cityFactor: 1,
    flatness: 0.9,
    economyFactor: 1.6,
    safetyScore: 0.2,
  },
  forest: {
    label: 'Forest',
    color: '#2d6a4f',
    icon: '🌲',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1.2,
    logisticsCost: 1.65,
    logisticsRisk: 0.7,
    baseSuitability: null,
    clusterMin: 10,
    baseWeight: 0.2,
    cityFactor: 0.7,
    flatness: 0.7,
    economyFactor: 1.0,
    safetyScore: -0.1,
  },
  swamp: {
    label: 'Swamp',
    color: '#4a7c59',
    icon: '🐊',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1.5,
    logisticsCost: 2.8,
    logisticsRisk: 1.2,
    baseSuitability: 0.34,
    clusterMin: 6,
    baseWeight: 0.3,
    cityFactor: 0.32,
    flatness: 0.5,
    economyFactor: 0.6,
    safetyScore: -0.5,
  },
  hills: {
    label: 'Hill',
    color: '#a47148',
    icon: '⛰️',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1.2,
    logisticsCost: 2.15,
    logisticsRisk: 0,
    baseSuitability: null,
    clusterMin: 7,
    baseWeight: 0.42,
    cityFactor: 0.45,
    flatness: 0.45,
    economyFactor: 0.9,
    safetyScore: -0.05,
  },
  plateau: {
    label: 'Plateau',
    color: '#c2936a',
    icon: '🪨',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 1.35,
    logisticsRisk: 0,
    baseSuitability: null,
    clusterMin: 7,
    baseWeight: 0.38,
    cityFactor: 0.3,
    flatness: 0.64,
    economyFactor: 0.8,
    safetyScore: 0.1,
  },
  mountains: {
    label: 'Mountain',
    color: '#5d4037',
    icon: '🏔️',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1.5,
    logisticsCost: 4.2,
    logisticsRisk: 1.4,
    baseSuitability: 0.14,
    clusterMin: 8,
    baseWeight: 0.1,
    cityFactor: 0.16,
    flatness: 0.2,
    economyFactor: 0.5,
    safetyScore: -0.2,
  },
  volcanic: {
    label: 'Volcanic',
    color: '#3e2723',
    icon: '🌋',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1.5,
    logisticsCost: 4.8,
    logisticsRisk: 1.4,
    baseSuitability: 0.18,
    clusterMin: 4,
    baseWeight: 0.1,
    cityFactor: 0.16,
    flatness: 0.2,
    economyFactor: 1.1,
    safetyScore: -0.8,
  },
  desert: {
    label: 'Desert',
    color: '#ffb300',
    icon: '🏜️',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 2.3,
    logisticsRisk: 0,
    baseSuitability: 0.22,
    clusterMin: 6,
    baseWeight: 0.04,
    cityFactor: 0.14,
    flatness: 0.6,
    economyFactor: 0.3,
    safetyScore: -0.3,
  },
  badlands: {
    label: 'Badlands',
    color: '#d84315',
    icon: '🪨',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 2.3,
    logisticsRisk: 0,
    baseSuitability: 0.18,
    clusterMin: 5,
    baseWeight: 0.04,
    cityFactor: 0.14,
    flatness: 0.35,
    economyFactor: 0.2,
    safetyScore: -0.4,
  },
  tundra: {
    label: 'Tundra',
    color: '#eceff1',
    icon: '❄️',
    isHydrologyWater: false,
    isMarineWater: false,
    isRenderWater: false,
    sizeFactor: 1,
    logisticsCost: 2.6,
    logisticsRisk: 0.7,
    baseSuitability: 0.14,
    baseWeight: 0.06,
    cityFactor: 0.2,
    flatness: 0.5,
    economyFactor: 0.5,
    safetyScore: -0.25,
  },
};

function validateTerrainConfigShape() {
  for (const [terrain, config] of Object.entries(TERRAIN_CONFIG)) {
    if (typeof config.baseWeight !== 'number')
      throw new Error(`Invalid terrain baseWeight: ${terrain}`);
    if (typeof config.cityFactor !== 'number')
      throw new Error(`Invalid terrain cityFactor: ${terrain}`);
    if (typeof config.flatness !== 'number')
      throw new Error(`Invalid terrain flatness: ${terrain}`);
    if (typeof config.safetyScore !== 'number')
      throw new Error(`Invalid terrain safetyScore: ${terrain}`);
    if (typeof config.logisticsCost !== 'number')
      throw new Error(`Invalid terrain logisticsCost: ${terrain}`);
    if (typeof config.logisticsRisk !== 'number')
      throw new Error(`Invalid terrain logisticsRisk: ${terrain}`);
    if (typeof config.sizeFactor !== 'number')
      throw new Error(`Invalid terrain sizeFactor: ${terrain}`);
    if (typeof config.isHydrologyWater !== 'boolean')
      throw new Error(`Invalid terrain isHydrologyWater: ${terrain}`);
    if (typeof config.isMarineWater !== 'boolean')
      throw new Error(`Invalid terrain isMarineWater: ${terrain}`);
    if (typeof config.isRenderWater !== 'boolean')
      throw new Error(`Invalid terrain isRenderWater: ${terrain}`);
  }
}

if (process.env.NODE_ENV !== 'production') {
  validateTerrainConfigShape();
}
