import {
  TBorderConfig,
  TBorderType,
  TDisplaySettings,
  TTerrainPreset,
  TTerrainRatioMap,
} from 'src/types/map.types';

export const NATION_COLORS = [
  '#e6194b',
  '#3cb44b',
  '#ffe119',
  '#4363d8',
  '#f58231',
  '#911eb4',
  '#46f0f0',
  '#f032e6',
  '#bcf60c',
  '#fabebe',
  '#008080',
  '#e6beff',
  '#9a6324',
  '#fffac8',
  '#800000',
  '#aaffc3',
  '#808000',
  '#ffd8b1',
  '#4D4DC1',
  '#808080',
  '#ffffff',
  '#ffd700',
  '#00ff7f',
  '#ff1493',
  '#ff4500',
  '#2e8b57',
  '#8b008b',
  '#daa520',
  '#00ced1',
  '#ff8c00',
  '#adff2f',
  '#ff00ff',
  '#1e90ff',
  '#fa8072',
  '#7fffd4',
  '#b22222',
  '#ffdead',
  '#4b0082',
  '#006400',
  '#bc8f8f',
];

export const DEFAULT_CONFIG: {
  seed: string;
  cellCount: number;
  seaLevel: number;
  terrainPreset: TTerrainPreset;
  nationCount: number;
  terrainRatios: TTerrainRatioMap;
  displaySettings: TDisplaySettings;
} = {
  seed: 'world-001',
  cellCount: 10000,
  seaLevel: 0.5,
  terrainPreset: 'balanced',
  nationCount: 8,
  terrainRatios: {
    plains: 0.35,
    forest: 0.2,
    swamp: 0.12,
    desert: 0.07,
    hills: 0.1,
    mountains: 0.08,
    plateau: 0.08,
  },
  displaySettings: {
    terrain: true,
    populationHeatmap: false,
    temperatureHeatmap: false,
    precipitationHeatmap: false,
    rainShadowHeatmap: false,
    economyHeatmap: false,
    rivers: false,
    countryBorders: false,
    countryFill: false,
    provinceBorders: false,
    ethnicBorders: false,
    ethnicFill: false,
    ethnicLabels: false,
    labels: false,
    cellData: false,
  },
};

export const MAP_VIEWPORT_CONFIG = {
  width: 1200,
  height: 760,
  minCells: 100,
  maxCells: 10000,
};

export const TERRAIN_THRESHOLDS = {
  deepWaterDepth: 0.15,
  coastBand: 0.02,
  plainsMax: 0.62,
  hillsMax: 0.76,
  mountainsMax: 0.9,
};

export const TOPOGRAPHY_CONFIG = {
  boundary: {
    collisionBaseCount: 7,
    collisionExtraCount: 4,
    riftBaseCount: 4,
    riftExtraCount: 3,
    halfLengthMin: 0.11,
    halfLengthRange: 0.25,
    strengthBase: 0.75,
    strengthRange: 0.6,
    influenceWidth: 0.12,
    collisionScale: 0.26,
    riftScale: 0.2,
  },
  seeds: {
    upliftCount: 10,
    basinCount: 8,
    xMargin: 0.03,
    yMargin: 0.03,
    span: 0.94,
    upliftRadiusBase: 0.06,
    upliftRadiusRange: 0.1,
    basinRadiusBase: 0.08,
    basinRadiusRange: 0.12,
    upliftAmplitudeBase: 0.2,
    upliftAmplitudeRange: 0.22,
    basinAmplitudeBase: 0.16,
    basinAmplitudeRange: 0.18,
  },
  warp: {
    frequency: 2.2,
    strength: 0.2,
    secondaryFrequency: 5.1,
    secondaryStrength: 0.08,
  },
  noise: {
    macroDivisor: 1.58,
    secondaryFrequency: 1.6,
    secondaryDivisor: 1.95,
    coastFrequency: 8.4,
    jaggedFrequency: 5.2,
    jaggedBase: 0.72,
    jaggedRange: 0.62,
    fbm: {
      octaves: 8,
      persistence: 0.53,
      lacunarity: 2.08,
    },
    ridged: {
      octaves: 7,
      persistence: 0.49,
      lacunarity: 2.2,
      sharpness: 1.75,
    },
    billow: {
      octaves: 7,
      persistence: 0.5,
      lacunarity: 1.96,
    },
  },
  shelf: {
    edgeOffset: 0.005,
    edgeRange: 0.18,
    weight: 0.05,
  },
  blend: {
    macro: 0.3,
    secondary: 0.18,
    ridged: 0.22,
    billow: 0.14,
    erosionMask: 0.12,
    upliftField: 0.3,
    tectonicUplift: 0.38,
    coastNoise: 0.08,
    basinField: 0.26,
    tectonicRift: 0.24,
    maxUplift: 1.2,
    maxRift: 1,
  },
  mountainRecovery: {
    quantileStart: 0.86,
    peakBoostMax: 0.14,
  },
};

export const PRESET_CONFIG = {
  balanced: {
    rangeBands: { count: 7, amplitude: 0.2, width: 0.11 },
    valleyBands: { count: 5, depth: 0.12, width: 0.12 },
    edgeShelfStrength: 0.24,
    smoothFactor: 0.2,
  },
  ranges: {
    rangeBands: { count: 10, amplitude: 0.24, width: 0.09 },
    valleyBands: { count: 4, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.2,
    smoothFactor: 0.16,
  },
  rifted: {
    rangeBands: { count: 8, amplitude: 0.17, width: 0.1 },
    valleyBands: { count: 8, depth: 0.16, width: 0.08 },
    globalScale: { offset: -0.02, scale: 0.98 },
    edgeShelfStrength: 0.22,
    smoothFactor: 0.18,
  },
  archipelago: {
    majorIslandMin: 1,
    majorIslandMax: 2,
    mediumIslandBase: 4,
    mediumIslandExtra: 3,
    smallIslandBase: 16,
    smallIslandExtra: 8,
    valleyBands: { count: 7, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.3,
    smoothFactor: 0.14,
  },
};

export const HYDROLOGY_CONFIG = {
  coastOutlet: -2,
  waterInfluenceIters: 6,
  waterInfluenceSelfW: 1.2,
  rainShadowMinDiff: 0.03,
  rainShadowScale: 2.8,
  deepWaterDepth: 0.14,
  coastBand: 0.015,
  valleyReliefMax: -0.01,
  valleyPrecipMin: 0.42,
  tundraTempMax: 0.18,
  tundraElevMin: 0.9,
  mountainElevMin: 0.78,
  hillElevMin: 0.66,
  plateauElevMin: 0.68,
  mountainReliefMin: 0.075,
  hillReliefMin: 0.04,
  plateauReliefCap: 0.016,
  newLandBand: 0.06,
  desertTempMin: 0.54,
  desertPrecipMax: 0.18,
  desertRainShadowMin: 0.34,
  swampPrecipMin: 0.76,
  swampElevMax: 0.61,
  swampReliefCap: 0.009,
  forestPrecipMin: 0.56,
  erosionMax: 0.08,
  erosionSlopeW: 0.2,
  erosionFlowW: 0.012,
  depositRate: 0.42,
  lakeSinkFlowMin: 8.8,
  riverMinFlow: 5.3,
  dryRiverFlowPenalty: 2.4,
  dryRiverPrecipMax: 0.27,
  dryRiverRainShadowMin: 0.26,
  lakeExpandMaxCells: 5,
  lakeExpandElevSlack: 0.018,
  lakeExpandRainShadowMax: 0.34,
  lakeExpandPrecipMin: 0.28,
  lakeMaxCount: 12,
  largeLakeMin: 4,
  enclosedLakeMax: 199,
  enclosedWaterElevBuffer: 0.04,
  enclosedWaterDepthMin: 0.055,
  enclosedWaterShoreFactor: 0.7,
  enclosedWaterShoreMax: 0.09,
  riverSrcElevMin: 0.78,
  plainRiverSrcFlowMin: 3.8,
  tundraRiverSrcFlowMin: 4.8,
  riverMinLen: 6,
  riverLandThreshold: 2200,
  largeRiverMinOnLargeLand: 2,
  largeRiverMaxOnLargeLand: 3,
  smallRiverTargetOnLargeLand: 14,
  largeRiverCountOnSmallLand: 1,
  smallRiverTargetOnSmallLand: 5,
  riverMinCount: 16,
  largePlainMin: 90,
  vLargePlainMin: 50,
  largeRiverPlainBonus: 4,
  vLargePlainRiverBonus: 8.5,
  vLargePlainSeaBonus: 4.8,
  vLargePlainMinRivers: 10,
  riverLenPriorityW: 0.56,
  tribJoinBonus: 4.2,
  tribMaxOverlap: 1,
  inlandPlainTribMinFlow: 2.2,
  inlandPlainTribMinLen: 10,
  inlandPlainTribMaxPerPlain: 10,
  highlandExtendMaxSteps: 26,
  highlandExtendMinFlow: 1.6,
  highlandTargetElevMin: 0.64,
  relaxedRiverSrcElevDrop: 0.14,
  relaxedRiverMinLen: 4,
  relaxedRiverFlowMin: 2.8,
  tempLatW: 0.85,
  tempElevW: 0.72,
  tempWaterW: 0.08,
  precipWaterW: 0.56,
  precipLatW: 0.18,
  precipFlowW: 0.08,
  precipRainShadowW: 0.38,
  oroElevStart: 0.6,
  oroW: 0.25,
  oroMax: 0.25,
  region: {
    minBase: 6,
    minScale: 0.35,
    smoothPasses: 2,
    dominantMin: 3,
    dominantBonus: 0.24,
    currentBonus: 0.15,
    switchGap: 0.2,
  },
  terrainBalance: {
    plainsMinShare: 0.3,
    plainsMaxShare: 0.4,

    forestMinShare: 0.18,
    forestMaxShare: 0.26,

    swampMinShare: 0.12,
    swampMaxShare: 0.2,

    desertMinShare: 0.05,
    desertMaxShare: 0.1,

    badlandsMaxShare: 0.07,

    volcanicMaxShare: 0.04,

    hillsMinShare: 0.08,
    hillsMaxShare: 0.15,

    mountainsMinShare: 0.06,
    mountainsMaxShare: 0.13,

    plateauMinShare: 0.05,
    plateauMaxShare: 0.1,
  },
  terrainClusterMinCells: {
    forest: 10,
    mountains: 8,
    hills: 7,
    swamp: 6,
    desert: 6,
    badlands: 5,
    volcanic: 4,
    valley: 5,
    plateau: 7,
  },
  antiAlias: { isolatedMax: 1, dominantMin: 3, passes: 2 },
};

export const RIVER_GEN_CONFIG = {
  minFluxToFormRiver: 30,
  landWaterThreshold: 0.2,
  cellsNumberModifierExp: 0.25,
  depression: {
    maxIterations: 200,
    epsilon: 0.0001,
    coastLift: 0.0015,
  },
  width: {
    fluxFactor: 500,
    maxFluxWidth: 1,
    lengthFactor: 200,
    minWidth: 0.8,
    maxWidth: 4.8,
  },
  meander: {
    base: 0.5,
    minSegmentLength: 16,
  },
  minRiverCells: 6,
};

export const BORDER_CONFIG: Record<TBorderType, TBorderConfig> = {
  country: {
    cost: {
      plains: 1.1,
      valley: 0.95,
      coast: 0.9,
      forest: 1.2,
      swamp: 1.9,
      hills: 1.9,
      plateau: 1.8,
      mountains: 7.8,
      volcanic: 8.6,
      desert: 2.1,
      badlands: 2.4,
      tundra: 1.8,
      lake: 1.2,
      'deep-water': 1.2,
      'shallow-water': 1.2,
      'inland-sea': 1.2,
    },
    penalty: { riverCross: 7.8, lakeCross: 8.4, ridgeCross: 10.5, shorelineEdgeBias: -0.3 },
    fragmentation: {
      maxMountainOwnersPerCluster: 2,
      largeMountainClusterMinCells: 10,
      clusterSplitPenalty: 2.8,
    },
    smoothness: { edgeNoiseWeight: 0.16, jaggedPenalty: 0.5 },
  },
  province: {
    cost: {
      plains: 1,
      valley: 0.95,
      coast: 1.15,
      forest: 1.35,
      swamp: 1.85,
      hills: 1.6,
      plateau: 1.7,
      mountains: 3.5,
      volcanic: 4.2,
      desert: 1.9,
      badlands: 2.1,
      tundra: 1.6,
      lake: 1.2,
      'deep-water': 1.2,
      'shallow-water': 1.2,
      'inland-sea': 1.2,
    },
    penalty: { riverCross: 3.4, lakeCross: 4.2, ridgeCross: 4.8, shorelineEdgeBias: -0.2 },
    fragmentation: {
      maxMountainOwnersPerCluster: 3,
      largeMountainClusterMinCells: 7,
      clusterSplitPenalty: 1.4,
    },
    smoothness: { edgeNoiseWeight: 0.08, jaggedPenalty: 0.25 },
  },
};

export const GEOPOLITICAL_CONFIG = {
  targetLandCellsPerNation: 620,
  minNationLandRatio: 0,
  minNationLandCells: 10,
  territorialRadiusMinCells: 3,
  territorialRadiusMaxCells: 3,
  narrowStraitThresholdCells: 6,
  frontierNoiseWeight: 0.22,
  hubCount: { smallNationMinLand: 450, mediumNationMinLand: 900, maxHubsPerNation: 3 },
  ethnic: {
    majorGroupCountMin: 6,
    majorGroupCountMax: 12,
    dominantShareMin: 0.5,
    dominantShareMax: 0.8,
    secondaryShareMin: 0.1,
    secondaryShareMax: 0.3,
    crossBorderBlend: 0.72,
    fragmentationLevel: 0.38,
    terrainInfluenceStrength: 1,
    distancePenalty: 0.045,
    smoothingPasses: 1,
    minorityClusterMinCells: 5,
  },
};
