import { TMapRenderMode, TTerrainPreset } from 'src/types/global';

export const MAP_EXPLORER_DEFAULT_CONFIG: {
  seed: string;
  cellCount: number;
  seaLevel: number;
  terrainPreset: TTerrainPreset;
  renderMode: TMapRenderMode;
} = {
  seed: 'world-001',
  cellCount: 7000,
  seaLevel: 0.46,
  terrainPreset: 'balanced',
  renderMode: 'seamless',
};

export const MAP_VIEWPORT_CONFIG = {
  width: 1200,
  height: 760,
  minCells: 100,
  maxCells: 10000,
};

export const MAP_TERRAIN_CLASSIFICATION_CONFIG = {
  deepWaterOffset: 0.15,
  coastBand: 0.02,
  plainsMax: 0.62,
  hillsMax: 0.76,
  mountainsMax: 0.9,
};

export const MAP_TOPOGRAPHY_CONFIG = {
  boundary: {
    collisionBaseCount: 7,
    collisionExtraCount: 4,
    riftBaseCount: 4,
    riftExtraCount: 3,
    halfLengthMin: 0.11,
    halfLengthRange: 0.25,
    strengthBase: 0.75,
    strengthRange: 0.6,
    influenceWidth: 0.12,
    collisionScale: 0.26,
    riftScale: 0.2,
  },
  seeds: {
    upliftCount: 10,
    basinCount: 8,
    xMargin: 0.03,
    yMargin: 0.03,
    span: 0.94,
    upliftRadiusBase: 0.06,
    upliftRadiusRange: 0.1,
    basinRadiusBase: 0.08,
    basinRadiusRange: 0.12,
    upliftAmplitudeBase: 0.2,
    upliftAmplitudeRange: 0.22,
    basinAmplitudeBase: 0.16,
    basinAmplitudeRange: 0.18,
  },
  warp: {
    frequency: 2.2,
    strength: 0.2,
    secondaryFrequency: 5.1,
    secondaryStrength: 0.08,
  },
  noise: {
    macroDivisor: 1.58,
    secondaryFrequency: 1.6,
    secondaryDivisor: 1.95,
    coastFrequency: 8.4,
    jaggedFrequency: 5.2,
    jaggedBase: 0.72,
    jaggedRange: 0.62,
    fbm: {
      octaves: 8,
      persistence: 0.53,
      lacunarity: 2.08,
    },
    ridged: {
      octaves: 7,
      persistence: 0.49,
      lacunarity: 2.2,
      sharpness: 1.75,
    },
    billow: {
      octaves: 7,
      persistence: 0.5,
      lacunarity: 1.96,
    },
  },
  shelf: {
    edgeOffset: 0.005,
    edgeRange: 0.18,
    weight: 0.05,
  },
  blend: {
    macro: 0.3,
    secondary: 0.18,
    ridged: 0.22,
    billow: 0.14,
    erosionMask: 0.12,
    upliftField: 0.3,
    tectonicUplift: 0.38,
    coastNoise: 0.08,
    basinField: 0.26,
    tectonicRift: 0.24,
    maxUplift: 1.2,
    maxRift: 1,
  },
};

export const MAP_PRESET_CONFIG = {
  balanced: {
    rangeBands: { count: 7, amplitude: 0.2, width: 0.11 },
    valleyBands: { count: 5, depth: 0.12, width: 0.12 },
    edgeShelfStrength: 0.24,
    smoothFactor: 0.2,
  },
  ranges: {
    rangeBands: { count: 10, amplitude: 0.24, width: 0.09 },
    valleyBands: { count: 4, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.2,
    smoothFactor: 0.16,
  },
  rifted: {
    rangeBands: { count: 8, amplitude: 0.17, width: 0.1 },
    valleyBands: { count: 8, depth: 0.16, width: 0.08 },
    globalScale: { offset: -0.02, scale: 0.98 },
    edgeShelfStrength: 0.22,
    smoothFactor: 0.18,
  },
  archipelago: {
    majorIslandMin: 1,
    majorIslandMax: 2,
    mediumIslandBase: 4,
    mediumIslandExtra: 3,
    smallIslandBase: 16,
    smallIslandExtra: 8,
    valleyBands: { count: 7, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.3,
    smoothFactor: 0.14,
  },
};

export const MAP_HYDROLOGY_CONFIG = {
  coastOutletId: -2,
  waterInfluenceIterations: 6,
  waterInfluenceSelfWeight: 1.2,
  rainShadowMinElevationDelta: 0.03,
  rainShadowScale: 2.8,
  deepWaterOffset: 0.14,
  coastBand: 0.015,
  valleyReliefThreshold: -0.01,
  valleyPrecipitationMin: 0.42,
  tundraTemperatureMax: 0.18,
  tundraElevationMin: 0.9,
  mountainElevationMin: 0.78,
  hillElevationMin: 0.66,
  plateauElevationMin: 0.68,
  reliefMountainMin: 0.075,
  reliefHillMin: 0.04,
  plateauReliefMax: 0.016,
  emergedLandBand: 0.06,
  desertTemperatureMin: 0.54,
  desertPrecipitationMax: 0.18,
  desertRainShadowMin: 0.34,
  swampPrecipitationMin: 0.76,
  swampElevationMax: 0.61,
  swampReliefMax: 0.009,
  forestPrecipitationMin: 0.56,
  erosionMax: 0.08,
  erosionSlopeWeight: 0.2,
  erosionFlowWeight: 0.012,
  depositFactor: 0.42,
  lakeSinkFlowMin: 8.8,
  lakeSinkPrecipitationMin: 0.62,
  riverFlowMin: 5.3,
  dryRiverFlowPenalty: 2.4,
  dryRiverPrecipitationMax: 0.27,
  dryRiverRainShadowMin: 0.26,
  lakeExpansionMaxCells: 5,
  lakeExpansionElevationSlack: 0.018,
  lakeExpansionRainShadowMax: 0.34,
  lakeExpansionPrecipitationMin: 0.28,
  maxLakeCount: 12,
  largeLakeMinCells: 4,
  riverSourceElevationMin: 0.78,
  plainRiverSourceFlowMin: 3.8,
  tundraRiverSourceFlowMin: 4.8,
  riverMinLength: 3,
  riverTargetLandThreshold: 2200,
  largeRiverMinCountLargeLand: 2,
  largeRiverMaxCountLargeLand: 3,
  smallRiverTargetLargeLand: 14,
  largeRiverCountSmallLand: 1,
  smallRiverTargetSmallLand: 5,
  minRiverCount: 16,
  largePlainMinCells: 90,
  veryLargePlainMinCells: 50,
  largeRiverPlainPriorityBonus: 4,
  veryLargePlainRiverBonus: 8.5,
  veryLargePlainSeaOutletBonus: 4.8,
  veryLargePlainMinRiverCount: 10,
  riverLengthPriorityWeight: 0.34,
  tributaryJoinBonus: 4.2,
  tributaryMaxOverlapRatio: 1,
  inlandPlainTributaryMinFlow: 2.2,
  inlandPlainTributaryMinLength: 7,
  inlandPlainTributaryMaxPerPlain: 10,
  highlandRiverExtensionMaxSteps: 16,
  highlandRiverExtensionMinFlow: 1.6,
  highlandRiverTargetElevationMin: 0.64,
  relaxedRiverSourceElevationDrop: 0.14,
  relaxedRiverMinLength: 2,
  relaxedRiverFlowMin: 2.8,
  temperatureLatitudeWeight: 0.85,
  temperatureElevationWeight: 0.72,
  temperatureWaterWeight: 0.08,
  precipitationWaterWeight: 0.56,
  precipitationLatitudeWeight: 0.18,
  precipitationFlowWeight: 0.08,
  precipitationRainShadowWeight: 0.38,
  orographicElevationStart: 0.6,
  orographicWeight: 0.25,
  orographicMax: 0.25,
  regionalization: {
    minRegionBase: 6,
    minRegionScale: 0.35,
    smoothingPasses: 2,
    dominantMinCount: 3,
    dominantScoreBonus: 0.24,
    currentScoreBonus: 0.15,
    switchMargin: 0.2,
  },
  terrainBalance: {
    plainsMinShare: 0.52,
    plainsMaxShare: 0.72,
    forestMinShare: 0.1,
    forestMaxShare: 0.2,
    swampMaxShare: 0.06,
    desertMaxShare: 0.05,
    badlandsMaxShare: 0.07,
    volcanicMaxShare: 0.03,
    hillsMaxShare: 0.18,
    mountainsMaxShare: 0.1,
    plateauMinShare: 0.04,
    plateauMaxShare: 0.13,
  },
  terrainClusterMinCells: {
    forest: 10,
    mountains: 8,
    hills: 7,
    swamp: 6,
    desert: 6,
    badlands: 5,
    volcanic: 4,
    valley: 5,
    plateau: 7,
  },
  antiAlias: {
    isolatedNeighborMax: 1,
    dominantNeighborMin: 3,
    passes: 2,
  },
};

export const MAP_GEOPOLITICAL_CONFIG = {
  nationCountMin: 3,
  nationCountMax: 7,
  targetLandCellsPerNation: 620,
  minNationLandRatio: 0.07,
  minNationLandCells: 180,
  territorialRadiusMinCells: 3,
  territorialRadiusMaxCells: 3,
  narrowStraitThresholdCells: 6,
  frontierNoiseWeight: 0.22,
  terrainCost: {
    plains: 1,
    valley: 0.9,
    coast: 1,
    forest: 1.1,
    swamp: 1.45,
    hills: 1.35,
    plateau: 1.3,
    mountains: 2.1,
    volcanic: 2.3,
    desert: 1.4,
    badlands: 1.5,
    tundra: 1.35,
  },
  barrierCost: {
    river: 1.35,
    ridge: 1.65,
    biomeBreak: 0.4,
  },
  hubCount: {
    smallNationMinLand: 450,
    mediumNationMinLand: 900,
    maxHubsPerNation: 3,
  },
};
