export const TOPOGRAPHY_CONFIG = {
  tectonic: {
    boundaryInfluenceWidth: 0.12,
    convergentUpliftScale: 0.35,
    divergentRiftScale: 0.2,
    subductionArcBoost: 1.6,
    continentalElevationBias: 0.03,
    oceanicElevationBias: 0.06,
  },
  seeds: {
    upliftCount: 10,
    basinCount: 8,
    xMargin: 0.03,
    yMargin: 0.03,
    span: 0.94,
    upliftRadiusBase: 0.06,
    upliftRadiusRange: 0.1,
    basinRadiusBase: 0.08,
    basinRadiusRange: 0.12,
    upliftAmplitudeBase: 0.2,
    upliftAmplitudeRange: 0.22,
    basinAmplitudeBase: 0.16,
    basinAmplitudeRange: 0.18,
  },
  warp: { frequency: 2.2, strength: 0.2, secondaryFrequency: 5.1, secondaryStrength: 0.08 },
  noise: {
    macroDivisor: 1.58,
    secondaryFrequency: 1.6,
    secondaryDivisor: 1.95,
    coastFrequency: 8.4,
    jaggedFrequency: 5.2,
    jaggedBase: 0.72,
    jaggedRange: 0.62,
    fbm: { octaves: 5, persistence: 0.55, lacunarity: 2.08 },
    ridged: { octaves: 5, persistence: 0.52, lacunarity: 2.2, sharpness: 1.75 },
    billow: { octaves: 5, persistence: 0.52, lacunarity: 1.96 },
  },
  shelf: { edgeOffset: 0.005, edgeRange: 0.18, weight: 0.05 },
  blend: {
    macro: 0.3,
    secondary: 0.18,
    ridged: 0.22,
    billow: 0.14,
    erosionMask: 0.12,
    upliftField: 0.3,
    tectonicUplift: 0.38,
    coastNoise: 0.08,
    basinField: 0.26,
    tectonicRift: 0.24,
    maxUplift: 1.2,
    maxRift: 1,
    continentalBias: 0.5,
    isostatic: 0.4,
  },
  mountainRecovery: { quantileStart: 0.86, peakBoostMax: 0.14 },
  erosion: {
    passCount: 2,
    sedimentCapacityFactor: 3.0,
    erosionRate: 0.2,
    depositionRate: 0.3,
    evaporationRate: 0.05,
    maxParticleSteps: 30,
    initialWaterVolume: 1.0,
    minSlope: 0.0005,
  },
};

export const TOPOGRAPHY_PRESET_CONFIG = {
  balanced: {
    rangeBands: { count: 7, amplitude: 0.2, width: 0.11 },
    valleyBands: { count: 5, depth: 0.12, width: 0.12 },
    edgeShelfStrength: 0.24,
    smoothFactor: 0.2,
  },
  ranges: {
    rangeBands: { count: 10, amplitude: 0.24, width: 0.09 },
    valleyBands: { count: 4, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.2,
    smoothFactor: 0.16,
  },
  rifted: {
    rangeBands: { count: 8, amplitude: 0.17, width: 0.1 },
    valleyBands: { count: 8, depth: 0.16, width: 0.08 },
    globalScale: { offset: -0.02, scale: 0.98 },
    edgeShelfStrength: 0.22,
    smoothFactor: 0.18,
  },
  archipelago: {
    majorIslandMin: 1,
    majorIslandMax: 2,
    mediumIslandBase: 4,
    mediumIslandExtra: 3,
    smallIslandBase: 16,
    smallIslandExtra: 8,
    valleyBands: { count: 7, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.3,
    smoothFactor: 0.14,
  },
  volcanic: {
    rangeBands: { count: 6, amplitude: 0.18, width: 0.08 },
    valleyBands: { count: 6, depth: 0.14, width: 0.09 },
    globalScale: { offset: -0.01, scale: 1.0 },
    edgeShelfStrength: 0.26,
    smoothFactor: 0.12,
  },
  continental: {
    plateauCount: 3,
    rangeBands: { count: 5, amplitude: 0.15, width: 0.14 },
    valleyBands: { count: 6, depth: 0.08, width: 0.15 },
    globalScale: { offset: 0.01, scale: 0.96 },
    edgeShelfStrength: 0.2,
    smoothFactor: 0.22,
  },
};
