export const TOPOGRAPHY_CONFIG = {
  boundary: {
    collisionBaseCount: 7,
    collisionExtraCount: 4,
    riftBaseCount: 4,
    riftExtraCount: 3,
    halfLengthMin: 0.11,
    halfLengthRange: 0.25,
    strengthBase: 0.75,
    strengthRange: 0.6,
    influenceWidth: 0.12,
    collisionScale: 0.26,
    riftScale: 0.2,
  },
  seeds: {
    upliftCount: 10,
    basinCount: 8,
    xMargin: 0.03,
    yMargin: 0.03,
    span: 0.94,
    upliftRadiusBase: 0.06,
    upliftRadiusRange: 0.1,
    basinRadiusBase: 0.08,
    basinRadiusRange: 0.12,
    upliftAmplitudeBase: 0.2,
    upliftAmplitudeRange: 0.22,
    basinAmplitudeBase: 0.16,
    basinAmplitudeRange: 0.18,
  },
  warp: { frequency: 2.2, strength: 0.2, secondaryFrequency: 5.1, secondaryStrength: 0.08 },
  noise: {
    macroDivisor: 1.58,
    secondaryFrequency: 1.6,
    secondaryDivisor: 1.95,
    coastFrequency: 8.4,
    jaggedFrequency: 5.2,
    jaggedBase: 0.72,
    jaggedRange: 0.62,
    fbm: { octaves: 8, persistence: 0.53, lacunarity: 2.08 },
    ridged: { octaves: 7, persistence: 0.49, lacunarity: 2.2, sharpness: 1.75 },
    billow: { octaves: 7, persistence: 0.5, lacunarity: 1.96 },
  },
  shelf: { edgeOffset: 0.005, edgeRange: 0.18, weight: 0.05 },
  blend: {
    macro: 0.3,
    secondary: 0.18,
    ridged: 0.22,
    billow: 0.14,
    erosionMask: 0.12,
    upliftField: 0.3,
    tectonicUplift: 0.38,
    coastNoise: 0.08,
    basinField: 0.26,
    tectonicRift: 0.24,
    maxUplift: 1.2,
    maxRift: 1,
  },
  mountainRecovery: { quantileStart: 0.86, peakBoostMax: 0.14 },
};

export const TOPOGRAPHY_PRESET_CONFIG = {
  balanced: {
    rangeBands: { count: 7, amplitude: 0.2, width: 0.11 },
    valleyBands: { count: 5, depth: 0.12, width: 0.12 },
    edgeShelfStrength: 0.24,
    smoothFactor: 0.2,
  },
  ranges: {
    rangeBands: { count: 10, amplitude: 0.24, width: 0.09 },
    valleyBands: { count: 4, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.2,
    smoothFactor: 0.16,
  },
  rifted: {
    rangeBands: { count: 8, amplitude: 0.17, width: 0.1 },
    valleyBands: { count: 8, depth: 0.16, width: 0.08 },
    globalScale: { offset: -0.02, scale: 0.98 },
    edgeShelfStrength: 0.22,
    smoothFactor: 0.18,
  },
  archipelago: {
    majorIslandMin: 1,
    majorIslandMax: 2,
    mediumIslandBase: 4,
    mediumIslandExtra: 3,
    smallIslandBase: 16,
    smallIslandExtra: 8,
    valleyBands: { count: 7, depth: 0.1, width: 0.1 },
    edgeShelfStrength: 0.3,
    smoothFactor: 0.14,
  },
};
